# Generated by Django 5.2.1 on 2025-06-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
